language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - ant

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false