language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
#  - 7.4
#  - 8.0
#  - nightly

addons:
  apt:
    packages:
      ant

matrix:
  fast_finish: true
#  allowed_failures:
#  - php: nightly
#    - php: 8.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - ant

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  email: false
